name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      # - name: check GITHUB_REF matches package version
      #   uses: samuelcolvin/check-python-version@v4.1
      #   with:
      #     version_file_path: pyproject.toml

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build release distributions
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
